#!/bin/bash
cd $(dirname $0)

git submodule init
git submodule update

stow_files=("nvim" "tmux" "git" "profile")
for folder in ${stow_files[@]}; do
	echo "stow $folder"
    stow -D $folder
    stow $folder
done

source ~/.bash_profile
